# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation

"""Apptainer deployment strategy."""

from __future__ import annotations

import logging
import os
import shlex
import signal
import subprocess
import time
from pathlib import Path
from typing import IO, List

from ..context import WizardContext
from ..schema import WizardApptainerConfig
from ..services import ContainerDefinition, build_container_set
from ..utils import resolve_apptainer_image
from .dispatcher import OsDispatchError

logger = logging.getLogger(__name__)

# Grace period between SIGTERM and SIGKILL when tearing down services.
_TERMINATE_GRACE_S = 10


class ApptainerDeployment:
    """Deployment strategy using Apptainer (formerly Singularity).

    Apptainer runs containers unprivileged as the calling user, which makes this
    the backend of choice on hosts and HPC clusters without a Docker daemon.
    Every container in the container set becomes one ``apptainer exec``
    invocation: services start in the background, the runtime runs in the
    foreground, and its exit status decides the outcome of the deployment.
    Services are torn down when the runtime exits.

    Apptainer deliberately ignores an image's ``WORKDIR``, ``USER`` and ``ENV``,
    so the working directory and environment are passed explicitly. Images are
    resolved from ``wizard.apptainer.image_caches`` and may otherwise be pulled
    from a registry. See docs/APPTAINER.md.
    """

    def __init__(self, context: WizardContext):
        """Initialize with context and build container set.

        Args:
            context: The wizard context
        """
        self.context = context
        self.container_set = build_container_set(context, use_address_string="0.0.0.0")
        self._background: list[tuple[str, subprocess.Popen[bytes]]] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def deploy_all_services(self) -> None:
        """Start services, run the runtime to completion, then stop services."""
        self.generate_run_script()

        services = [c for c in self.container_set.sim if c.command != "noop"]
        runtime = self.container_set.runtime

        dry_run = self.context.cfg.wizard.dry_run

        try:
            for container in services:
                self._launch_background(container)
            # Telemetry starts alongside the services but never gates the run:
            # an image without exporters should not stall the simulation.
            self._launch_background(self.container_set.prometheus)

            if not dry_run:
                self._wait_for_containers(services)

            if runtime is not None:
                self._run_foreground(runtime)
            elif not dry_run:
                # Services-only deployment (`run_sim_services` without
                # "runtime"), e.g. to drive them from a runtime running
                # elsewhere. Stay in the foreground so the services outlive this
                # call and are torn down when the user interrupts it.
                logger.info(
                    "No runtime container configured; serving %d service(s) "
                    "until interrupted",
                    len(services),
                )
                self._await_background()
        finally:
            self._terminate_background()

    def generate_run_script(self) -> Path:
        """Write a standalone ``run.sh`` reproducing this deployment.

        The script starts the services in the background, waits for their ports,
        runs the runtime in the foreground and cleans the services up on exit.
        It is self-contained, so it can be submitted with ``sbatch`` or run by
        hand without the wizard.

        Returns:
            Path to the generated script.
        """
        services = [c for c in self.container_set.sim if c.command != "noop"]
        telemetry = self.container_set.prometheus
        runtime = self.container_set.runtime

        lines = [
            "#!/bin/bash",
            "# Generated by alpasim_wizard (run_method: APPTAINER). Do not edit.",
            "set -euo pipefail",
            "",
            "SERVICE_PIDS=()",
            "",
            "cleanup() {",
            "    [ ${#SERVICE_PIDS[@]} -eq 0 ] && return 0",
            '    kill "${SERVICE_PIDS[@]}" 2>/dev/null || true',
            '    wait "${SERVICE_PIDS[@]}" 2>/dev/null || true',
            "}",
            "trap cleanup EXIT",
            "",
            "wait_for_port() {",
            "    local host=$1 port=$2 deadline=$((SECONDS + $3))",
            '    until (exec 3<>"/dev/tcp/$host/$port") 2>/dev/null; do',
            '        if [ "$SECONDS" -gt "$deadline" ]; then',
            '            echo "Timed out waiting for $host:$port" >&2',
            "            exit 1",
            "        fi",
            "        sleep 1",
            "    done",
            "    exec 3>&-",
            "}",
            "",
            "# --- Services ---",
        ]

        for container in [*services, telemetry]:
            lines += [
                f"# {container.uuid}",
                f"{self.apptainer_command(container)} &",
                "SERVICE_PIDS+=($!)",
                "",
            ]

        if runtime is not None:
            timeout = self.context.cfg.wizard.timeout or 600
            # Telemetry is excluded on purpose, matching deploy_all_services.
            addresses = [
                address
                for container in services
                for address in container.get_all_addresses()
            ]
            if addresses:
                lines.append("# --- Wait for services ---")
                lines += [
                    f"wait_for_port {address.host} {address.port} {timeout}"
                    for address in addresses
                ]
                lines.append("")
            lines += [
                "# --- Runtime (foreground) ---",
                f"# {runtime.uuid}",
                self.apptainer_command(runtime),
            ]

        script_path = Path(self.context.cfg.wizard.log_dir) / "run.sh"
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        script_path.chmod(0o755)
        logger.info("Generated Apptainer run script: %s", script_path)
        return script_path

    # ------------------------------------------------------------------
    # Command construction
    # ------------------------------------------------------------------

    @property
    def config(self) -> WizardApptainerConfig:
        """Apptainer-specific settings from the wizard config."""
        apptainer_config: WizardApptainerConfig = self.context.cfg.wizard.apptainer
        return apptainer_config

    def apptainer_command(self, container: ContainerDefinition) -> str:
        """Build the shell command that runs a container under Apptainer.

        Args:
            container: ContainerDefinition instance

        Returns:
            A single shell command, safe to pass to a shell as-is.
        """
        config = self.config
        image = self._resolve_image(container)

        args: list[str] = [shlex.quote(config.binary), "exec"]

        # GPU passthrough. Mirrors the Docker Compose backend: containers pinned
        # to a GPU see exactly that device, and the telemetry container sees all
        # of them so the GPU exporters have something to report.
        if container.gpu is not None:
            args += ["--nv", f"--env CUDA_VISIBLE_DEVICES={container.gpu}"]
        elif container.name == "prometheus" and self.context.num_gpus > 0:
            args.append("--nv")

        args += [
            f"--bind {shlex.quote(volume.to_str())}" for volume in container.volumes
        ]

        # Apptainer ignores the image's WORKDIR and starts in the host CWD. The
        # configured default lives in the alpasim images only, so images from
        # elsewhere run from `/` unless their service config names a directory.
        workdir = container.workdir or (
            "/" if container.service_config.external_image else config.workdir
        )
        args.append(f"--pwd {shlex.quote(workdir)}")

        for env in list(config.environments) + list(container.environments or []):
            if "=" in env:
                args.append(f"--env {shlex.quote(env)}")
            else:
                # Pass-through from the host. Defaults to empty rather than
                # failing, so `set -u` in the generated run.sh is safe.
                args.append(f'--env {env}="${{{env}-}}"')

        args += list(config.extra_exec_args)

        # Writable scratch for paths outside the bind mounts. An overlay is
        # created on first use, so re-runs reuse the existing one.
        setup = ""
        overlay = self._overlay_path(container, image)
        if overlay is not None:
            setup = (
                f"[ -f {shlex.quote(str(overlay))} ] || "
                f"{shlex.quote(config.binary)} overlay create "
                f"--size {config.overlay_size_mb} {shlex.quote(str(overlay))}; "
            )
            args.append(f"--overlay {shlex.quote(str(overlay))}")
        elif config.writable_tmpfs:
            args.append("--writable-tmpfs")

        args.append(shlex.quote(image) if os.path.isabs(image) else image)

        if container.command and container.command != "noop":
            # Same unescaping as the SLURM backend: `$$` marks a `$` that the
            # service, not the wizard's config parser, should interpret.
            command = container.command.replace("$$", "$")
            args.append(f"bash -c {shlex.quote(command)}")

        return setup + " ".join(args)

    def _resolve_image(self, container: ContainerDefinition) -> str:
        """Resolve a container's image to a local path or ``docker://`` URI."""
        config = self.config
        return resolve_apptainer_image(
            container.service_config.image,
            list(config.image_caches),
            registry_fallback=config.registry_fallback,
        )

    def _overlay_path(self, container: ContainerDefinition, image: str) -> Path | None:
        """Return the overlay image for a container, or None for tmpfs scratch.

        Matches against the resolved image, so patterns work for both cached
        paths and registry references. Creates the containing directory, since
        the command created here is what fills it.
        """
        patterns = self.config.overlay_image_patterns
        if not any(pattern in image for pattern in patterns):
            return None
        overlay = (
            Path(self.context.cfg.wizard.log_dir)
            / "apptainer-overlays"
            / f"{container.uuid}.img"
        )
        overlay.parent.mkdir(parents=True, exist_ok=True)
        return overlay

    # ------------------------------------------------------------------
    # Process management
    # ------------------------------------------------------------------

    def _log_file(self, container: ContainerDefinition) -> Path:
        """Per-container output log, mirroring the SLURM backend's layout."""
        log_dir = Path(self.context.cfg.wizard.log_dir) / "txt-logs"
        log_dir.mkdir(parents=True, exist_ok=True)
        return log_dir / f"out-{container.uuid}-log.txt"

    def _launch_background(self, container: ContainerDefinition) -> None:
        """Start a service container without waiting for it."""
        command = self.apptainer_command(container)

        if self.context.cfg.wizard.dry_run:
            logger.info("[DRY-RUN] Would execute: %s", command)
            return

        log_file = self._log_file(container)
        logger.info("Starting %s (output -> %s)", container.uuid, log_file)
        with open(log_file, "ab") as handle:
            process = self._popen(command, handle)
        self._background.append((container.uuid, process))

    def _run_foreground(self, container: ContainerDefinition) -> None:
        """Run a container to completion, raising if it fails."""
        command = self.apptainer_command(container)

        if self.context.cfg.wizard.dry_run:
            logger.info("[DRY-RUN] Would execute: %s", command)
            return

        log_file = self._log_file(container)
        logger.info("Running %s (output -> %s)", container.uuid, log_file)
        with open(log_file, "ab") as handle:
            process = self._popen(command, handle)
            return_code = process.wait()

        if return_code != 0:
            raise OsDispatchError(
                f"Container {container.uuid} failed with return code "
                f"{return_code}; see {log_file}"
            )

    def _popen(self, command: str, log_file: IO[bytes]) -> subprocess.Popen[bytes]:
        """Start a command in its own process group, logging to a file.

        The new session is what makes teardown reliable: signalling the group
        reaches the shell, ``apptainer`` and the container's processes, not just
        the shell the wizard spawned.
        """
        return subprocess.Popen(
            command,
            shell=True,
            stdout=log_file,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )

    def _await_background(self) -> None:
        """Block until every background service has exited."""
        for uuid, process in self._background:
            return_code = process.wait()
            logger.info("%s exited with return code %d", uuid, return_code)

    def _terminate_background(self) -> None:
        """Stop background services, escalating to SIGKILL if needed."""
        if not self._background:
            return

        logger.info("Stopping %d Apptainer service(s)", len(self._background))
        for uuid, process in self._background:
            self._signal_group(uuid, process, signal.SIGTERM)

        deadline = time.monotonic() + _TERMINATE_GRACE_S
        for uuid, process in self._background:
            remaining = max(0.0, deadline - time.monotonic())
            try:
                process.wait(timeout=remaining)
            except subprocess.TimeoutExpired:
                logger.warning("%s did not stop on SIGTERM; killing", uuid)
                self._signal_group(uuid, process, signal.SIGKILL)

        self._background.clear()

    def _signal_group(
        self, uuid: str, process: subprocess.Popen[bytes], sig: signal.Signals
    ) -> None:
        """Signal a launched process group, tolerating already-exited services."""
        try:
            os.killpg(os.getpgid(process.pid), sig)
        except (ProcessLookupError, PermissionError) as error:
            logger.debug("Could not signal %s: %s", uuid, error)

    # ------------------------------------------------------------------
    # Waiting
    # ------------------------------------------------------------------

    def _wait_for_containers(
        self,
        containers: List[ContainerDefinition],
        timeout: int | None = None,
    ) -> None:
        """Wait until every container's service addresses accept connections."""
        if timeout is None:
            timeout = self.context.cfg.wizard.timeout

        logger.info("Waiting for Apptainer services to become ready...")
        waited = 0
        for container in containers:
            for address in container.get_all_addresses():
                while not address.is_open():
                    self._assert_still_running(container)
                    time.sleep(1)
                    waited += 1
                    if timeout is not None and waited > timeout:
                        raise TimeoutError(
                            f"Service {container.name} at {address} did not "
                            f"become ready within {timeout}s; see "
                            f"{self._log_file(container)}"
                        )
                logger.info("  %s ready.", address)
        logger.info("All Apptainer services ready.")

    def _assert_still_running(self, container: ContainerDefinition) -> None:
        """Fail fast when a service exits instead of waiting out the timeout."""
        for uuid, process in self._background:
            if uuid != container.uuid:
                continue
            return_code = process.poll()
            if return_code is not None:
                raise OsDispatchError(
                    f"Container {uuid} exited with return code {return_code} "
                    f"while starting up; see {self._log_file(container)}"
                )
